source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

workspace 'Omnom.xcworkspace'

inhibit_all_warnings!

xcodeproj 'Omnom/omnom.xcodeproj'
xcodeproj 'OMNSocial/Example/OMNSocial.xcodeproj'
xcodeproj 'OMNStyler/Example/OMNStyler.xcodeproj'
xcodeproj 'OMNCardEnterControl/Example/OMNCardEnterControl.xcodeproj'
xcodeproj 'OMNBeacon/Example/OMNBeacon.xcodeproj'
xcodeproj 'OMNSocketIO/Example/OMNSocketIO.xcodeproj'


def import_pods
end

def import_all
  import_pods
  pod 'AFNetworking'
  pod 'SSKeychain'
  pod 'CardIO'
  pod 'BlocksKit'
  pod 'Mixpanel'
  pod 'TTTAttributedLabel'
  pod 'uidevice-extension'
  pod 'UIDevice-Hardware'
  pod 'libextobjc'
  pod 'CocoaLumberjack', '~> 2.0.0-rc'
  pod 'PromiseKit'
  pod "OMNStyler", :path => "OMNStyler/"
  pod "OMNCardEnterControl", :path => "OMNCardEnterControl/"
  pod "OMNBeacon", :path => "OMNBeacon/"
  pod "OMNSocketIO", :path => "OMNSocketIO/"
  pod "OMNMailRuAcquiring", :path => "OMNMailRuAcquiring/"
end

target 'omnom', :exclusive => true do
  import_all
  pod 'CrashlyticsFramework'
  pod 'SDWebImage'
  xcodeproj 'Omnom/omnom.xcodeproj'
end

target 'omnomTests', :exclusive => true do
  import_all
  pod 'OCMock'
  pod 'KIF', '~> 3.0.4'
  pod 'Kiwi'
  xcodeproj 'Omnom/omnom.xcodeproj'
end

target 'OMNSocial', :exclusive => true do
  pod "OMNSocial", :path => "OMNSocial/"
  xcodeproj 'OMNSocial/Example/OMNSocial.xcodeproj'
end

target 'OMNStyler', :exclusive => true do
  pod "OMNStyler", :path => "OMNStyler/"
  xcodeproj 'OMNStyler/Example/OMNStyler.xcodeproj'
end

target 'OMNCardEnterControl', :exclusive => true do
  pod "OMNCardEnterControl", :path => "OMNCardEnterControl/"
  xcodeproj 'OMNCardEnterControl/Example/OMNCardEnterControl.xcodeproj'
end

target 'OMNBeacon', :exclusive => true do
  pod "OMNBeacon", :path => "OMNBeacon/"
  xcodeproj 'OMNBeacon/Example/OMNBeacon.xcodeproj'
end

target 'OMNMailRuAcquiring', :exclusive => true do
  pod "OMNMailRuAcquiring", :path => "OMNMailRuAcquiring/"
  xcodeproj 'OMNMailRuAcquiring/Example/OMNMailRuAcquiring.xcodeproj'
end

target 'OMNMailRuAcquiringTests', :exclusive => true do
  pod "OMNMailRuAcquiring", :path => "OMNMailRuAcquiring/"
  pod 'Kiwi'
  xcodeproj 'OMNMailRuAcquiring/Example/OMNMailRuAcquiring.xcodeproj'
end

target 'OMNSocketIO', :exclusive => true do
  pod "OMNSocketIO", :path => "OMNSocketIO/"
  xcodeproj 'OMNSocketIO/Example/OMNSocketIO.xcodeproj'
end
