target 'OMNMailRuAcquiring', :exclusive => true do
  pod "OMNMailRuAcquiring", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "OMNMailRuAcquiring", :path => "../"
  
  pod 'Kiwi/XCTest'
end
