platform :ios, '7.0'

workspace 'Omnom.xcworkspace'

inhibit_all_warnings!

xcodeproj 'beacon/beacon.xcodeproj'
xcodeproj 'test/test.xcodeproj'
xcodeproj 'restaurants/restaurants.xcodeproj'
xcodeproj 'seocialtest/seocialtest.xcodeproj'


def import_pods
  pod 'EstimoteSDK', '~> 1.3.0'
  pod 'AFNetworking'
end

def import_all
  import_pods
  pod 'EstimoteSDK', '~> 1.3.0'
  pod 'AFNetworking'
  pod 'google-plus-ios-sdk'
  pod 'VK-ios-sdk'
  pod 'SSKeychain'
  pod 'CardIO'
  pod 'BlocksKit'
  pod 'TSCurrencyTextField'
  pod 'Mixpanel'
  pod 'UrbanAirship-iOS-SDK'
  pod "OMNStyler", :path => "../OMNStyler/"
  pod "OMNCardEnterControl", :path => "../OMNCardEnterControl/"
  pod "OMNBeacon", :path => "../OMNBeacon/"
  
end

target :restaurants do
  import_all
  pod 'EAIntroView'
  xcodeproj 'restaurants/restaurants.xcodeproj'
end

target :restaurantsTests do
  import_pods
  pod 'OCMock'
  pod 'KIF', '~> 3.0.4'
  xcodeproj 'restaurants/restaurants.xcodeproj'
end

target :seocialtest do
  import_all
  xcodeproj 'seocialtest/seocialtest.xcodeproj'
end