platform :ios, '7.0'

workspace 'Omnom.xcworkspace'

inhibit_all_warnings!

xcodeproj 'restaurants/omnom.xcodeproj'
xcodeproj '../OMNSocial/Example/OMNSocial.xcodeproj'
xcodeproj '../OMNStyler/Example/OMNStyler.xcodeproj'
xcodeproj '../OMNCardEnterControl/Example/OMNCardEnterControl.xcodeproj'
xcodeproj '../OMNBeacon/Example/OMNBeacon.xcodeproj'


def import_pods
end

def import_all
  import_pods
  pod 'AFNetworking'
  pod 'SSKeychain'
  pod 'CardIO'
  pod 'BlocksKit'
  pod 'TSCurrencyTextField'
  pod 'Mixpanel'
  pod 'UrbanAirship-iOS-SDK'
  pod "OMNStyler", :path => "../OMNStyler/"
  pod "OMNCardEnterControl", :path => "../OMNCardEnterControl/"
  pod "OMNBeacon", :path => "../OMNBeacon/"
  pod "OMNSocial", :path => "../OMNSocial/"
  
end

target :omnom do
  import_all
  pod 'EAIntroView'
  xcodeproj 'restaurants/omnom.xcodeproj'
end

target :omnomTests do
  import_pods
  pod 'OCMock'
  pod 'KIF', '~> 3.0.4'
  xcodeproj 'restaurants/omnom.xcodeproj'
end

target :OMNSocial do
  pod "OMNSocial", :path => "../OMNSocial/"
  xcodeproj '../OMNSocial/Example/OMNSocial.xcodeproj'
end

target :OMNStyler do
  pod "OMNStyler", :path => "../OMNStyler/"
  xcodeproj '../OMNStyler/Example/OMNStyler.xcodeproj'
end

target :OMNCardEnterControl do
  pod "OMNCardEnterControl", :path => "../OMNCardEnterControl/"
  xcodeproj '../OMNCardEnterControl/Example/OMNCardEnterControl.xcodeproj'
end

target :OMNBeacon do
  pod "OMNBeacon", :path => "../OMNBeacon/"
  xcodeproj '../OMNBeacon/Example/OMNBeacon.xcodeproj'
end